{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certo.fullname" . }}-db
  labels:
    {{- include "certo.labels" . | nindent 4 }}
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.password | quote }}
{{- end }}
